---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pod-html
  namespace: test
  labels:
    app: pod
    type: pod
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: nfs-sc
  resources:
    requests:
      storage: 8Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pod-data
  namespace: test
  labels:
    app: pod
    type: pod
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: nfs-sc
  resources:
    requests:
      storage: 8Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: pod
  namespace: test
  labels:
    app: pod
    type: pod
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: nginx-html
      mountPath: /usr/share/nginx/html/
    - name: nginx-data
      mountPath: /data
  volumes:
  - name: nginx-html
    persistentVolumeClaim:
      claimName: pod-html
  - name: nginx-data
    persistentVolumeClaim:
      claimName: pod-data
