apiVersion: batch/v1
kind: Job
metadata:
  name: echo
  namespace: test
  labels:
    job-name: echo
spec:
  ttlSecondsAfterFinished: 100
  backoffLimit: 4
  completions: 1
  parallelism: 1
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: echo
        image: busybox
        imagePullPolicy: IfNotPresent
        command:
        - sh
        - -c
        - >
          echo "hello job";
          sleep 10
          exit 1
        resources: {}
