---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test
  namespace: test
  labels:
    type: persistentvolumeclaim
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: nfs-sc
  resources:
    requests:
      storage: 6Gi
